### ISSUE TITLE
Build Module and Property Type Documentation.

### ISSUE THREAD

**Issue by ryanmrichard** [NWChemEx/.github#107]
The ultimate goal of this issue is to update [build_docs.sh](https://github.com/NWChemEx-Project/.github/blob/master/actions/build_docs/build_docs.sh) so that the deployed documentation contains the documentation for the modules in the plugin. 

- Step 1 is https://github.com/NWChemEx-Project/PluginPlay/issues/305
- With python bindings available, one can generate the documentation with a trivial Python script:
  ```
  import pluginplay
  import my_plugin
  mm = pluginplay.ModuleManager()
  my_plugin.load_modules(mm)
  pluginplay.document_modules(mm, "where to put files")
  ```
  - `my_plugin` would need to be replaced with the name of the plugin as exposed to Python
  - workflow would be: build and install plugin, call aforementioned Python script, build and deploy documentation.
- The workflows for for integrals, ChemCache, and SCF need to be updated to generate module documentation; however, the implemented solution needs to be general and easily adapted to new plugins as they are written.

**Comment by jwaldrop107** [comment]
This has been handled in the current CI workflows.
